ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "activity_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invitations" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "vehicles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "stations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "station_hours" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "service_slots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "station_fuel_prices" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "fuel_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fuel_request_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "request_status_events" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "store_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "store_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "station_store_items" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;
